spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/jobboard
    username: anuranpaul
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
    
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes in milliseconds
    cache-names: jobSearches,jobs,popularTags